CONFIG:
  TPLAYOUT: configs/dd/conf_frcnn_layout.yaml
  TPCELL: configs/dd/conf_frcnn_cell.yaml
  TPITEM: configs/dd/conf_frcnn_rows.yaml
  TESS_OCR: configs/dd/conf_tesseract.yaml
WEIGHTS:
  TPLAYOUT: layout/model-2026500.data-00000-of-00001
  TPCELL: cell/model-2840000.data-00000-of-00001
  TPITEM: item/model-1750000.data-00000-of-00001
SEGMENTATION:
  ASSIGNMENT_RULE: ioa
  IOU_THRESHOLD_ROWS: 0.01
  IOU_THRESHOLD_COLS: 0.001
  IOA_THRESHOLD_ROWS: 0.4
  IOA_THRESHOLD_COLS: 0.4
  FULL_TABLE_TILING: True
  REMOVE_IOU_THRESHOLD_ROWS: 0.001
  REMOVE_IOU_THRESHOLD_COLS: 0.001
WORD_MATCHING:
  PARENTAL_CATEGORIES:
    - TEXT
    - TITLE
    - CELL
    - LIST
  RULE: ioa
  IOU_THRESHOLD: 0.001
  IOA_THRESHOLD: 0.9