USE_PDF_MINER: True
USE_OCR: True
USE_LAYOUT: True
USE_TABLE_SEGMENTATION: True
USE_TABLE_REFINEMENT: True

LIB: "PT"
DEVICE: "cpu"

PT:
  LAYOUT:
    WEIGHTS: "deepdoctection/d2_casc_rcnn_X_32xd4_50_FPN_GN_2FC_publaynet_inference_only"
    FILTER: []

OCR:
  USE_TESSERACT: True
  USE_DOCTR: False
  USE_TEXTRACT: False
  CONFIG:
    TESSERACT: "conf_tesseract.yaml"