WEIGHTS:
  TF:
     LAYOUT: layout/model-800000_inf_only.data-00000-of-00001
     CELL: cell/model-1800000_inf_only.data-00000-of-00001
     ITEM: item/model-1620000_inf_only.data-00000-of-00001
  PT:
     LAYOUT: layout/d2_model_0829999_layout_inf_only.pt
     CELL: cell/d2_model_1849999_cell_inf_only.pt
     ITEM: item/d2_model_1639999_item_inf_only.pt
USE_TABLE_SEGMENTATION: True
SEGMENTATION:
  ASSIGNMENT_RULE: ioa
  THRESHOLD_ROWS: 0.4
  THRESHOLD_COLS: 0.4
  FULL_TABLE_TILING: True
  REMOVE_IOU_THRESHOLD_ROWS: 0.001
  REMOVE_IOU_THRESHOLD_COLS: 0.001
USE_TABLE_REFINEMENT: True
USE_OCR: True
CONFIG:
  TESS_OCR: dd/conf_tesseract.yaml
WORD_MATCHING:
  PARENTAL_CATEGORIES:
    - text
    - title
    - cell
    - list
  RULE: ioa
  THRESHOLD: 0.6
TEXT_ORDERING:
  TEXT_CONTAINER: word
  TEXT_BLOCK_CATEGORIES:
    - title
    - text
    - list
    - cell
  FLOATING_TEXT_BLOCK_CATEGORIES:
    - title
    - text
    - list
  INCLUDE_RESIDUAL_TEXT_CONTAINER: False
  STARTING_POINT_TOLERANCE: 0.005
  BROKEN_LINE_TOLERANCE: 0.003
  HEIGHT_TOLERANCE: 2.0
  PARAGRAPH_BREAK: 0.035
