name: Upload to PyPi

on:
  release:
    types: [published]

jobs:
  pypi-check:
    if: "!github.event.release.prerelease"
    runs-on: ubuntu-latest
    needs: upload-pypi

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: x64

    - name: Install package
      run: python3 -m pip install --upgrade pip
           pip install deepdoctection
           python -c "import deepdoctection; print(deepdoctection.__version__)"